[ls]
".js" = "kebab-case"
".jsx" = "kebab-case"
".ts" = "kebab-case"
".tsx" = "kebab-case"
".html" = "kebab-case"
".css" = "kebab-case | snake_case"
".scss" = "kebab-case"
".sh" = "kebab-case"
".svg" = "kebab-case"
".cjs" = "regex:use-js-instead"
".mjs" = "regex:use-js-instead"
".md" = "kebab-case | SCREAMING_SNAKE_CASE | snake_case"
".dir" = "kebab-case | snake_case"

ignore = [
  ".agent",
  ".gemini",
  ".git",
  ".github",
  ".husky",
  ".moon",
  ".specify",
  ".vscode",
  "node_modules",
  "apps/client/tests/e2e/.features-gen",
  "tempcontext",
  "**/.turbo",
  "**/__screenshots__",
  "**/build",
  "**/coverage",
  "**/dev-dist",
  "**/dist",
  "**/node_modules",
]
